import JSZip from "jszip";
import type {
  CaptionRecord,
  Clip,
  MotionGraphicRecord,
  ProjectRecord,
  Scene,
  ThumbnailRecord,
  VideoMetadataRecord,
  Voiceover,
  ManifestSummary,
} from "./studio-context";
import { manifestToMarkdown, type ManifestData, formatTimecode } from "./manifest";
import { formatSRTTime } from "./captions";

export type ExportSelections = {
  manifest_json: boolean;
  manifest_pdf: boolean;
  manifest_markdown: boolean;
  editor_brief: boolean;
  metadata_json: boolean;
  full_srt: boolean;
  per_scene_srt: boolean;
  voiceovers: boolean;
  clip_references: boolean;
  ai_images: boolean;
  hera_videos: boolean;
  motion_graphic_specs: boolean;
  ai_clip_prompts: boolean;
  thumbnail_concepts: boolean;
  youtube_metadata: boolean;
  platform_copy: boolean;
};

export type ExportPlatform = "youtube" | "youtube_shorts" | "linkedin" | "twitter";

export const PLATFORM_LABELS: Record<ExportPlatform, string> = {
  youtube: "YouTube (16:9)",
  youtube_shorts: "YouTube Shorts (9:16)",
  linkedin: "LinkedIn (16:9)",
  twitter: "Twitter (16:9 compressed)",
};

export const PLATFORM_NOTES: Record<ExportPlatform, string> = {
  youtube: "YouTube (16:9): Standard 1920x1080 export. 30fps, H.264, AAC 320kbps audio.",
  youtube_shorts:
    "YouTube Shorts (9:16): Identify strongest 60-second moment. Reformat to 9:16 vertical. Add captions (required for Shorts). Recommend the highest-tension scene.",
  linkedin:
    "LinkedIn (16:9): Trim to under 10 minutes. Add captions (autoplay muted). First 3 seconds must work without sound.",
  twitter:
    "Twitter / X (16:9 compressed): Trim to under 2 minutes 20 seconds. Compress for web. Captions required.",
};

export type ExportInputs = {
  project: ProjectRecord;
  scenes: Scene[];
  voiceovers: Voiceover[];
  clips: Clip[];
  motionGraphics: MotionGraphicRecord[];
  captions: CaptionRecord[];
  manifest: ManifestSummary | null;
  thumbnail: ThumbnailRecord | null;
  videoMetadata: VideoMetadataRecord | null;
};

export function slugify(s: string): string {
  return (s || "project")
    .replace(/[^a-z0-9]+/gi, "_")
    .toLowerCase()
    .replace(/^_|_$/g, "");
}

function sceneNumberOf(scenes: Scene[], scene_id: string): number {
  const s = scenes.find((x) => x.id === scene_id);
  return s ? s.scene_index + 1 : 0;
}

function pad2(n: number) {
  return String(n).padStart(2, "0");
}

/* ------------------------------ TEXT BUILDERS ----------------------------- */

export function buildEditorBriefTxt(manifest: ManifestData, project: ProjectRecord): string {
  const m = manifest;
  return `EDITOR BRIEF

Project: ${m.project.title}
Duration: ${m.project.total_duration_formatted}
Target: ${project.target_duration ?? "—"}
Generated by DocForge

STYLE
${m.editor_brief.overview}

COLOR GRADE
${m.editor_brief.color_grade}

PACING
${m.editor_brief.pacing_notes}

MUSIC
${m.editor_brief.music_notes}

EXPORT SPECS
YouTube: 1920x1080, 30fps, H.264
Audio: AAC 320kbps

SCENE SUMMARY
Total scenes: ${m.assembly_summary.total_scenes}
Motion graphics: ${m.assembly_summary.asset_breakdown.motion_graphic_scenes}
AI images: ${m.assembly_summary.asset_breakdown.ai_image_scenes}
YouTube clips: ${m.assembly_summary.asset_breakdown.youtube_scenes}
Real footage: ${m.assembly_summary.real_footage_percentage}%

WARNINGS
${m.assembly_summary.warnings.length ? m.assembly_summary.warnings.join("\n") : "None"}
`;
}

export function buildYouTubeMetadataTxt(meta: VideoMetadataRecord): string {
  const titles = meta.titles as { text?: string }[];
  const firstTitle =
    typeof titles?.[0] === "string" ? (titles[0] as unknown as string) : titles?.[0]?.text;
  return `YOUTUBE METADATA
Generated by DocForge

TITLE
${meta.selected_title ?? firstTitle ?? ""}

DESCRIPTION
${meta.description ?? ""}

${(meta.hashtags ?? []).join(" ")}

TAGS
${(meta.tags ?? []).join(", ")}

CHAPTERS
${(meta.chapters ?? []).map((c) => `${c.time} ${c.title}`).join("\n")}
`;
}

export function buildPlatformCopyTxt(meta: VideoMetadataRecord): string {
  const v = (meta.platform_variations ?? {}) as Record<string, Record<string, string>>;
  const li = v.linkedin ?? {};
  const tw = v.twitter ?? {};
  const sh = v.youtube_shorts ?? {};
  return `PLATFORM COPY
Generated by DocForge

LINKEDIN
${li.hook ?? ""}

${li.body ?? ""}

${li.cta ?? ""}

---

TWITTER / X
${tw.tweet ?? ""}

THREAD OPENER
${tw.thread_opener ?? ""}

---

YOUTUBE SHORTS
Hook: ${sh.hook ?? ""}
Description: ${sh.description ?? ""}
`;
}

export function buildThumbnailConceptsTxt(thumb: ThumbnailRecord): string {
  const lines: string[] = ["THUMBNAIL CONCEPTS", "Generated by DocForge", ""];
  const concepts = (thumb.concepts ?? []) as Record<string, unknown>[];
  concepts.forEach((c, i) => {
    const selected = thumb.selected_concept_index === i ? " (SELECTED)" : "";
    lines.push(`--- CONCEPT ${i + 1}${selected} ---`);
    if (c.title_copy) lines.push(`Title overlay: ${String(c.title_copy)}`);
    if (c.concept) lines.push(`Concept: ${String(c.concept)}`);
    if (c.visual_description) lines.push(`Visual: ${String(c.visual_description)}`);
    if (c.image_prompt) lines.push(`Image prompt: ${String(c.image_prompt)}`);
    if (c.image_url) lines.push(`Generated image: ${String(c.image_url)}`);
    lines.push("");
  });
  if (thumb.custom_title_copy) lines.push(`Custom title copy: ${thumb.custom_title_copy}`);
  return lines.join("\n");
}

export function buildAiClipPromptsTxt(scenes: Scene[], clips: Clip[]): string {
  const lines: string[] = ["AI CLIP PROMPTS", "Generated by DocForge", ""];
  for (const s of scenes) {
    const clip = clips.find((c) => c.scene_id === s.id);
    if (!s.clip_brief && !clip?.source_url) continue;
    lines.push(`SCENE ${s.scene_index + 1}`);
    lines.push(`Visual Job: ${s.visual_job ?? "—"}`);
    lines.push(`Subject: ${s.clip_brief?.subject ?? "—"}`);
    if (s.clip_brief?.mood?.length) lines.push(`Mood: ${s.clip_brief.mood.join(", ")}`);
    if (s.clip_brief?.avoid?.length) lines.push(`Avoid: ${s.clip_brief.avoid.join(", ")}`);
    if (s.clip_brief?.color_temperature) lines.push(`Color: ${s.clip_brief.color_temperature}`);
    if (s.clip_brief?.suggested_search_terms?.length) {
      lines.push("Search Terms:");
      for (const t of s.clip_brief.suggested_search_terms) lines.push(`  - ${t}`);
    }
    lines.push("---", "");
  }
  return lines.join("\n");
}

export function buildFullVideoSrt(scenes: Scene[], captions: CaptionRecord[]): string {
  const ordered = [...scenes].sort((a, b) => a.scene_index - b.scene_index);
  let timeOffset = 0;
  let idx = 1;
  const blocks: string[] = [];
  for (const scene of ordered) {
    const cap = captions.find((c) => c.scene_id === scene.id);
    const dur = scene.estimated_seconds ?? 0;
    if (cap?.caption_lines?.length) {
      for (const line of cap.caption_lines) {
        const start = formatSRTTime(line.start + timeOffset);
        const end = formatSRTTime(line.end + timeOffset);
        blocks.push(`${idx}\n${start} --> ${end}\n${line.text}\n`);
        idx += 1;
      }
    }
    timeOffset += dur;
  }
  return blocks.join("\n");
}

export function buildPlatformManifestNotes(platforms: ExportPlatform[]): string {
  if (!platforms.length) return "";
  return [
    "PLATFORM TARGETS",
    "Generated by DocForge",
    "",
    ...platforms.map((p) => `- ${PLATFORM_NOTES[p]}`),
  ].join("\n");
}

/* ------------------------------ FOLDER TREE ------------------------------- */

export function buildFolderPreview(
  selections: ExportSelections,
  inputs: ExportInputs,
  platforms: ExportPlatform[],
): string[] {
  const slug = slugify(inputs.project.title);
  const root = `${slug}_docforge_export`;
  const lines: string[] = [`/${root}/`];

  const docs: string[] = [];
  if (selections.manifest_json && inputs.manifest)
    docs.push(`manifest_v${inputs.manifest.version}.json`);
  if (selections.manifest_pdf && inputs.manifest)
    docs.push(`manifest_v${inputs.manifest.version}.pdf`);
  if (selections.manifest_markdown && inputs.manifest)
    docs.push(`manifest_v${inputs.manifest.version}.md`);
  if (selections.editor_brief && inputs.manifest) docs.push("editor_brief.txt");
  if (selections.metadata_json && inputs.videoMetadata) docs.push("metadata.json");
  if (platforms.length) docs.push("platform_targets.txt");
  if (docs.length) {
    lines.push("  /documents/");
    for (const f of docs) lines.push(`    ${f}`);
  }

  if (selections.voiceovers && inputs.voiceovers.length) {
    lines.push("  /audio/voiceovers/");
    lines.push("    voiceover_files.json");
    lines.push("    DOWNLOAD_INSTRUCTIONS.txt");
  }

  const vis: string[] = [];
  if (selections.clip_references) vis.push("clip_references.json");
  if (selections.ai_images) vis.push("ai_images.json");
  if (selections.hera_videos) vis.push("hera_videos.json");
  if (selections.motion_graphic_specs) vis.push("motion_graphic_specs.json");
  if (vis.length) {
    lines.push("  /visuals/");
    for (const f of vis) lines.push(`    ${f}`);
  }

  const prompts: string[] = [];
  if (selections.ai_clip_prompts) prompts.push("ai_clip_prompts.txt");
  if (selections.thumbnail_concepts && inputs.thumbnail) prompts.push("thumbnail_concepts.txt");
  if (prompts.length) {
    lines.push("  /prompts/");
    for (const f of prompts) lines.push(`    ${f}`);
  }

  const meta: string[] = [];
  if (selections.youtube_metadata && inputs.videoMetadata) meta.push("youtube_metadata.txt");
  if (selections.platform_copy && inputs.videoMetadata) meta.push("platform_copy.txt");
  if (meta.length) {
    lines.push("  /metadata/");
    for (const f of meta) lines.push(`    ${f}`);
  }

  const captionsHas = inputs.captions.length > 0;
  if ((selections.full_srt || selections.per_scene_srt) && captionsHas) {
    lines.push("  /captions/");
    if (selections.full_srt) lines.push("    full_video_captions.srt");
    if (selections.per_scene_srt) {
      lines.push("    /per_scene/");
      for (const s of [...inputs.scenes].sort((a, b) => a.scene_index - b.scene_index)) {
        const cap = inputs.captions.find((c) => c.scene_id === s.id);
        if (cap?.srt_content) lines.push(`      scene_${pad2(s.scene_index + 1)}_captions.srt`);
      }
    }
  }

  return lines;
}

export function countSelectedFiles(
  selections: ExportSelections,
  inputs: ExportInputs,
  platforms: ExportPlatform[],
): number {
  return buildFolderPreview(selections, inputs, platforms).filter((l) => !l.trim().endsWith("/"))
    .length;
}

export function estimatedSizeMB(selections: ExportSelections, inputs: ExportInputs): number {
  // Pure compilation — no media is embedded. Estimate JSON/text payload.
  let bytes = 0;
  if (selections.manifest_json && inputs.manifest)
    bytes += JSON.stringify(inputs.manifest.manifest_data ?? {}).length;
  if (selections.manifest_markdown && inputs.manifest) bytes += 8000;
  if (selections.editor_brief) bytes += 2000;
  if (selections.metadata_json && inputs.videoMetadata)
    bytes += JSON.stringify(inputs.videoMetadata).length;
  if (selections.clip_references) bytes += inputs.clips.length * 400;
  if (selections.ai_images) bytes += inputs.clips.length * 300;
  if (selections.hera_videos) bytes += inputs.clips.length * 200;
  if (selections.motion_graphic_specs) bytes += inputs.motionGraphics.length * 500;
  if (selections.ai_clip_prompts) bytes += inputs.scenes.length * 400;
  if (selections.thumbnail_concepts && inputs.thumbnail) bytes += 4000;
  if (selections.youtube_metadata && inputs.videoMetadata) bytes += 2000;
  if (selections.platform_copy && inputs.videoMetadata) bytes += 2000;
  if (selections.full_srt) bytes += inputs.captions.length * 2000;
  if (selections.per_scene_srt) bytes += inputs.captions.length * 2000;
  if (selections.voiceovers) bytes += inputs.voiceovers.length * 300;
  return Math.max(0.01, +(bytes / (1024 * 1024)).toFixed(2));
}

/* --------------------------- ASSET URL EXTRACTION ------------------------- */

export function collectAssetUrls(inputs: ExportInputs): string[] {
  const urls = new Set<string>();
  for (const v of inputs.voiceovers) if (v.audio_url) urls.add(v.audio_url);
  for (const c of inputs.clips) {
    if (c.source_url) urls.add(c.source_url);
    if (c.image_url) urls.add(c.image_url);
    if (c.animation_url) urls.add(c.animation_url);
    if (c.thumbnail_url) urls.add(c.thumbnail_url);
  }
  for (const mg of inputs.motionGraphics) if (mg.hera_output_url) urls.add(mg.hera_output_url);
  if (inputs.thumbnail) {
    for (const c of (inputs.thumbnail.concepts ?? []) as Record<string, unknown>[]) {
      if (typeof c.image_url === "string") urls.add(c.image_url);
    }
  }
  return Array.from(urls);
}

/* ------------------------------ ZIP BUILDER ------------------------------- */

export type ProgressFn = (msg: string) => void;

export async function buildExportZip(
  inputs: ExportInputs,
  selections: ExportSelections,
  platforms: ExportPlatform[],
  onProgress: ProgressFn,
): Promise<Blob> {
  const zip = new JSZip();
  const slug = slugify(inputs.project.title);
  const root = zip.folder(`${slug}_docforge_export`);
  if (!root) throw new Error("Failed to create zip root");

  // DOCUMENTS
  onProgress("Adding manifest…");
  const docs = root.folder("documents");
  if (docs && inputs.manifest) {
    const data = inputs.manifest.manifest_data as ManifestData;
    if (selections.manifest_json)
      docs.file(`manifest_v${inputs.manifest.version}.json`, JSON.stringify(data, null, 2));
    if (selections.manifest_markdown)
      docs.file(`manifest_v${inputs.manifest.version}.md`, manifestToMarkdown(data));
    if (selections.manifest_pdf) {
      // PDF generation requires a renderer; ship a print-ready HTML alongside the markdown.
      docs.file(
        `manifest_v${inputs.manifest.version}.pdf.html`,
        `<!doctype html><meta charset="utf-8"><title>Manifest v${inputs.manifest.version}</title><pre style="font-family:ui-monospace,Menlo,monospace;white-space:pre-wrap;padding:24px;">${escapeHtml(
          manifestToMarkdown(data),
        )}</pre><script>window.onload=()=>window.print();</script>`,
      );
    }
    if (selections.editor_brief)
      docs.file("editor_brief.txt", buildEditorBriefTxt(data, inputs.project));
  }
  if (selections.metadata_json && inputs.videoMetadata && docs) {
    docs.file("metadata.json", JSON.stringify(inputs.videoMetadata, null, 2));
  }
  if (platforms.length && docs) {
    docs.file("platform_targets.txt", buildPlatformManifestNotes(platforms));
  }

  // AUDIO
  if (selections.voiceovers && inputs.voiceovers.length) {
    onProgress("Adding voiceovers…");
    const audio = root.folder("audio")?.folder("voiceovers");
    if (audio) {
      const refs = inputs.voiceovers
        .filter((v) => v.audio_url)
        .map((v) => {
          const n = sceneNumberOf(inputs.scenes, v.scene_id);
          return {
            scene: n,
            filename: `scene_${pad2(n)}_voiceover.mp3`,
            url: v.audio_url,
            duration_seconds: v.duration_seconds,
            voice_name: v.voice_name,
            words_per_minute: v.words_per_minute,
          };
        })
        .sort((a, b) => a.scene - b.scene);
      audio.file("voiceover_files.json", JSON.stringify(refs, null, 2));
      audio.file(
        "DOWNLOAD_INSTRUCTIONS.txt",
        "Each voiceover is hosted as an MP3.\n" +
          "Download from the `url` field in voiceover_files.json,\n" +
          "and rename to the matching `filename`.\n",
      );
    }
  }

  // VISUALS
  onProgress("Adding visual references…");
  const visuals = root.folder("visuals");
  if (visuals) {
    if (selections.clip_references) {
      const refs = inputs.clips
        .filter((c) => c.asset_type === "youtube" || c.asset_type === "stock_footage")
        .map((c) => ({
          scene: sceneNumberOf(inputs.scenes, c.scene_id),
          type: c.asset_type,
          source: c.source_channel,
          title: c.source_title,
          url: c.source_url,
          timestamp_start: c.timestamp_start,
          timestamp_end: c.timestamp_end,
          duration_seconds: c.duration_seconds,
        }))
        .sort((a, b) => a.scene - b.scene);
      visuals.file("clip_references.json", JSON.stringify(refs, null, 2));
    }
    if (selections.ai_images) {
      const refs = inputs.clips
        .filter((c) => c.asset_type === "static_image" || c.image_url)
        .map((c) => ({
          scene: sceneNumberOf(inputs.scenes, c.scene_id),
          image_url: c.image_url,
          source: c.source_channel,
          ken_burns: c.ken_burns_config,
        }))
        .sort((a, b) => a.scene - b.scene);
      visuals.file("ai_images.json", JSON.stringify(refs, null, 2));
    }
    if (selections.hera_videos) {
      const refs = inputs.motionGraphics
        .filter((mg) => mg.hera_output_url)
        .map((mg) => ({
          scene: sceneNumberOf(inputs.scenes, mg.scene_id),
          graphic_type: mg.graphic_type,
          output_url: mg.hera_output_url,
          render_method: mg.render_method,
        }))
        .sort((a, b) => a.scene - b.scene);
      visuals.file("hera_videos.json", JSON.stringify(refs, null, 2));
    }
    if (selections.motion_graphic_specs) {
      const specs = inputs.motionGraphics.map((mg) => ({
        scene: sceneNumberOf(inputs.scenes, mg.scene_id),
        graphic_type: mg.graphic_type,
        graphic_data: mg.graphic_data,
        render_method: mg.render_method,
        remotion_component: mg.graphic_type
          .split("_")
          .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : ""))
          .join(""),
      }));
      visuals.file("motion_graphic_specs.json", JSON.stringify(specs, null, 2));
    }
  }

  // PROMPTS
  const prompts = root.folder("prompts");
  if (prompts) {
    if (selections.ai_clip_prompts) {
      prompts.file("ai_clip_prompts.txt", buildAiClipPromptsTxt(inputs.scenes, inputs.clips));
    }
    if (selections.thumbnail_concepts && inputs.thumbnail) {
      prompts.file("thumbnail_concepts.txt", buildThumbnailConceptsTxt(inputs.thumbnail));
    }
  }

  // METADATA
  if (inputs.videoMetadata) {
    const meta = root.folder("metadata");
    if (meta) {
      if (selections.youtube_metadata)
        meta.file("youtube_metadata.txt", buildYouTubeMetadataTxt(inputs.videoMetadata));
      if (selections.platform_copy)
        meta.file("platform_copy.txt", buildPlatformCopyTxt(inputs.videoMetadata));
    }
  }

  // CAPTIONS
  onProgress("Adding captions…");
  if (selections.full_srt && inputs.captions.length) {
    const captionsFolder = root.folder("captions");
    captionsFolder?.file(
      "full_video_captions.srt",
      buildFullVideoSrt(inputs.scenes, inputs.captions),
    );
  }
  if (selections.per_scene_srt && inputs.captions.length) {
    const perScene = root.folder("captions")?.folder("per_scene");
    if (perScene) {
      for (const s of [...inputs.scenes].sort((a, b) => a.scene_index - b.scene_index)) {
        const cap = inputs.captions.find((c) => c.scene_id === s.id);
        if (cap?.srt_content) {
          perScene.file(`scene_${pad2(s.scene_index + 1)}_captions.srt`, cap.srt_content);
        }
      }
    }
  }

  // README
  root.file(
    "README.txt",
    `DocForge Export Package
Project: ${inputs.project.title}
Duration: ${
      inputs.manifest
        ? formatTimecode(
            (inputs.manifest.manifest_data as ManifestData)?.project?.total_duration_seconds ?? 0,
          )
        : "—"
    }
Manifest version: ${inputs.manifest?.version ?? "—"}
Platforms: ${platforms.map((p) => PLATFORM_LABELS[p]).join(", ") || "—"}

All large media assets are referenced by URL.
See documents/, visuals/, audio/, captions/ for the full package.
`,
  );

  onProgress("Compressing…");
  const blob = await zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
  return blob;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function triggerDownload(blob: Blob, filename: string): string {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  // Return URL so caller can revoke later or use for "download again"
  return url;
}
